couchdb_data:
    image:
        centos
    volumes:
        - /data
        - /usr/local/var/log/couchdb
    command:
        echo "Data container for CouchDB Data volume /data"
couchdb_server:
    image:
        neogeo/couchdb
    environment:
        DATADIR: /data
        SUPERUSER: neogeo
        # SUPERPASS: yourpassword (see logs for randomly generated pwd)
    volumes_from:
        - couchdb_data
    ports:
        - "5984:5984"